### ISSUE TITLE
Getting methods

### ISSUE THREAD

**Issue by clod81** [tmm1/cycript#2]
Hi,
I'm quite new in iOS and cycrypt in general.
I'm trying to print methods in cycript of AppDelegate of an iOS application using http://iphonedevwiki.net/index.php/Cycript_Tricks#Getting_methods .
These are the steps I'm trying to follow:

```
var a = [UIApplication sharedApplication]
#"<UIApplication: 0x175b1e50>"
cy# a.delegate
#"<AppDelegate: 0x176b5890>"
cy# printMethods("AppDelegate")
```

After calling the printmethods function, cycript crashes. I tried this for 2 different applications, and I get the same error in both cases.

```
MS:Error: _krncall(mach_vm_read_overwrite(task, data, sizeof(*baton), reinterpret_cast<mach_vm_address_t>(baton), &error)) =4
*** _assert(status == 0):../Inject.cpp(143):InjectLibrary
```

I'm using a `iPad 4 gen, armv7`, iOS jailbroken version `8.0.2`.

Thanks

**Comment by locpv-ibl** [comment]
same here, has this solved?
